// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyActiveCode(arg1) {
  return window['go']['main']['App']['ApplyActiveCode'](arg1);
}

export function BatchPublishMedia(arg1) {
  return window['go']['main']['App']['BatchPublishMedia'](arg1);
}

export function CheckAccountStatus(arg1, arg2) {
  return window['go']['main']['App']['CheckAccountStatus'](arg1, arg2);
}

export function DetectBrowserStatus() {
  return window['go']['main']['App']['DetectBrowserStatus']();
}

export function GetAccountRiskStatus(arg1, arg2) {
  return window['go']['main']['App']['GetAccountRiskStatus'](arg1, arg2);
}

export function GetAuthOverview() {
  return window['go']['main']['App']['GetAuthOverview']();
}

export function GetDeviceID() {
  return window['go']['main']['App']['GetDeviceID']();
}

export function GetRiskOverview() {
  return window['go']['main']['App']['GetRiskOverview']();
}

export function LoginAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoginAccount'](arg1, arg2, arg3);
}

export function LoginAccountWithAppWindow(arg1, arg2) {
  return window['go']['main']['App']['LoginAccountWithAppWindow'](arg1, arg2);
}

export function LoginAccountWithScreencast(arg1, arg2) {
  return window['go']['main']['App']['LoginAccountWithScreencast'](arg1, arg2);
}

export function MatrixPublishMedia(arg1) {
  return window['go']['main']['App']['MatrixPublishMedia'](arg1);
}

export function PipelinePublishMedia(arg1) {
  return window['go']['main']['App']['PipelinePublishMedia'](arg1);
}

export function PublishMedia(arg1) {
  return window['go']['main']['App']['PublishMedia'](arg1);
}

export function ResumeAccount(arg1, arg2) {
  return window['go']['main']['App']['ResumeAccount'](arg1, arg2);
}

export function SelectLocalFile(arg1, arg2) {
  return window['go']['main']['App']['SelectLocalFile'](arg1, arg2);
}

export function SelectLocalFiles(arg1, arg2) {
  return window['go']['main']['App']['SelectLocalFiles'](arg1, arg2);
}

export function SendBrowserInput(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['main']['App']['SendBrowserInput'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function StopActivePublish() {
  return window['go']['main']['App']['StopActivePublish']();
}

export function StopSingleTask(arg1, arg2) {
  return window['go']['main']['App']['StopSingleTask'](arg1, arg2);
}

export function StopTaskById(arg1) {
  return window['go']['main']['App']['StopTaskById'](arg1);
}
