// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyActiveCode(arg1) {
  return window['go']['main']['App']['ApplyActiveCode'](arg1);
}

export function BatchPublishMedia(arg1) {
  return window['go']['main']['App']['BatchPublishMedia'](arg1);
}

export function CheckAccountStatus(arg1, arg2) {
  return window['go']['main']['App']['CheckAccountStatus'](arg1, arg2);
}

export function GetAuthOverview() {
  return window['go']['main']['App']['GetAuthOverview']();
}

export function GetDeviceID() {
  return window['go']['main']['App']['GetDeviceID']();
}

export function LoginAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoginAccount'](arg1, arg2, arg3);
}

export function MatrixPublishMedia(arg1) {
  return window['go']['main']['App']['MatrixPublishMedia'](arg1);
}

export function PipelinePublishMedia(arg1) {
  return window['go']['main']['App']['PipelinePublishMedia'](arg1);
}

export function PublishMedia(arg1) {
  return window['go']['main']['App']['PublishMedia'](arg1);
}

export function SelectLocalFile(arg1, arg2) {
  return window['go']['main']['App']['SelectLocalFile'](arg1, arg2);
}

export function StopActivePublish() {
  return window['go']['main']['App']['StopActivePublish']();
}

export function StopSingleTask(arg1, arg2) {
  return window['go']['main']['App']['StopSingleTask'](arg1, arg2);
}

export function StopTaskById(arg1) {
  return window['go']['main']['App']['StopTaskById'](arg1);
}
