// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';
import {engine} from '../models';

export function ApplyActiveCode(arg1:string):Promise<auth.AuthOverview>;

export function BatchPublishMedia(arg1:engine.BatchPublishParam):Promise<Array<engine.AccountPublishResult>>;

export function CheckAccountStatus(arg1:string,arg2:string):Promise<engine.AccountStatus>;

export function GetAuthOverview():Promise<auth.AuthOverview>;

export function GetDeviceID():Promise<string>;

export function LoginAccount(arg1:string,arg2:string,arg3:boolean):Promise<engine.LoginResult>;

export function MatrixPublishMedia(arg1:engine.MatrixPublishParam):Promise<Array<engine.AccountPublishResult>>;

export function PublishMedia(arg1:engine.PublishParam):Promise<string>;

export function SelectLocalFile(arg1:string,arg2:Array<string>):Promise<string>;

export function StopActivePublish():Promise<boolean>;
