// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchPublishMedia(arg1) {
  return window['go']['main']['App']['BatchPublishMedia'](arg1);
}

export function CheckAccountStatus(arg1, arg2) {
  return window['go']['main']['App']['CheckAccountStatus'](arg1, arg2);
}

export function LoginAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['LoginAccount'](arg1, arg2, arg3);
}

export function PublishMedia(arg1) {
  return window['go']['main']['App']['PublishMedia'](arg1);
}

export function SelectLocalFile(arg1, arg2) {
  return window['go']['main']['App']['SelectLocalFile'](arg1, arg2);
}

export function StopActivePublish() {
  return window['go']['main']['App']['StopActivePublish']();
}
